# Site settings
title: GSCFWID
motto: A follower now, a creator in future.
email: gscfwid@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A anesthesiologist, a researcher, a geek...
baseurl: "https://www.researchgate.net/profile/Shaowei_Gao2" # the subpath of your site, e.g. /blog/
url: "http://gscfwid.github.io" # the base hostname & protocol for your site
github_username:  gscfwid

# Build settings
markdown: kramdown
